### ISSUE TITLE
Some items in JEI but not on the furniture block

### ISSUE THREAD

**Issue by Sapfirelynx** [UnlikePaladin/paladin-furniture-mod#202]
### Bug Description

I am just trying to clarify because I saw these in jei, but they don't seem to be in the furniture block and was confused.

<img width="830" height="350" alt="Image" src="https://github.com/user-attachments/assets/2e15f23d-4393-476c-93d4-3dfffade04ed" />

### Reproduction Steps

I am in Forge 47.4.0 Minecraft version 1.20.1

### Log File

[launcher_log.txt](https://github.com/user-attachments/files/21265431/launcher_log.txt)

[latest.log](https://github.com/user-attachments/files/21265433/latest.log)

**Comment by UnlikePaladin** [comment]
They are, I've seen them before lol

**Comment by UnlikePaladin** [comment]
ohh you meant the crafter block, I'll check

**Comment by UnlikePaladin** [comment]
Yeah I see it in the crafter block :/

**Comment by UnlikePaladin** [comment]
Huh, they seem to be missing from 1.20.1 specifically, odd, I'll look into it

**Comment by Weirdexcepcion738** [comment]
i have the same issue but im playing in the 1.16.5

**Comment by UnlikePaladin** [comment]
This should've been fixed with 1.4.4, if it wasn't let me know

**Comment by CounselorCloud** [comment]
> This should've been fixed with 1.4.4, if it wasn't let me know

This was not fixed, at least testing on my server on 1.20.1

Edit to add: Can add more info as needed but I have tried 1.4.4 and it has not updated but all of the blocks are in REI (my server has REI and JEI)
