### ISSUE TITLE
[Minecraft 1.19.2 ] Loading error after upgrading to Paladin's Furniture 1.20

### ISSUE THREAD

**Issue by vesaliuz** [UnlikePaladin/paladin-furniture-mod#65]
After upgrading PFM to 1.2 I found the following error that stops my server´s start up:

java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "com.unlikepaladin.pfm.runtime.PFMRuntimeResources.RESOURCE_PACK_LIST" is null
        at com.unlikepaladin.pfm.runtime.PFMDataGenerator.run(PFMDataGenerator.java:35) ~[paladin-furniture-mod-1.2.0-fabric-mc1.19.jar:?]
        at com.unlikepaladin.pfm.runtime.PFMRuntimeResources.prepareAndRunDataGen(PFMRuntimeResources.java:85) ~[paladin-furniture-mod-1.2.0-fabric-mc1.19.jar:?]
        at net.fabricmc.fabric.impl.resource.loader.ModResourcePackCreator.md433ce3$pfm$lambda$addPFMResources$2$1(ModResourcePackCreator.java:541) ~[fabric-resource-loader-v0-0.8.4+edbdcddb90-cea1330ea25bf71.jar:?]
        at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183) ~[guava-31.0.1-jre.jar:?]
        at com.unlikepaladin.pfm.client.PathPackRPWrapper.close(PathPackRPWrapper.java:71) ~[paladin-furniture-mod-1.2.0-fabric-mc1.19.jar:?]
        at net.fabricmc.fabric.impl.resource.loader.ModResourcePackUtil.createDefaultDataPackSettings(ModResourcePackUtil.java:127) ~[fabric-resource-loader-v0-0.8.4+edbdcddb90-cea1330ea25bf71.jar:?]
        at net.minecraft.server.Main.redirect$bpd000$fabric-resource-loader-v0$replaceDefaultDataPackSettings(Main.java:2532) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:152) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.24.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.19.2-loader.0.14.24-launcher.0.11.2.jar:0.11.2]

Fabric loader version is 0.14.24 and Fabric Launcher is 0.11.2

**Comment by CantWeAllDisagree** [comment]
Tested with just fabric api and paladins furniture 1.2 on my server, got the same problem.

**Comment by UnlikePaladin** [comment]
Reuploading the jar to fix this problem, please check again in an hour

**Comment by UnlikePaladin** [comment]
Fixed, please redownload the jar from Modrinth

**Comment by vesaliuz** [comment]
Thank you for your quick response.
Just re-downloaded the jar and tested and issue persists.
